// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

type OmarchyInput struct {
	Args string `json:"args"`

	// expect_non_zero: assert the command FAILED (any non-zero exit) — the
	// CLI-rejects-X class. Mirrors plugin-command's expect_non_zero; mutually
	// exclusive with the step-level exit_status matcher (exact code).
	ExpectNonZero bool `json:"expect_non_zero"`
}
